# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dongyinan/Documents/biophysics/HIV/c++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dongyinan/Documents/biophysics/HIV/c++

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dongyinan/Documents/biophysics/HIV/c++/CMakeFiles /Users/dongyinan/Documents/biophysics/HIV/c++/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dongyinan/Documents/biophysics/HIV/c++/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shellgrow

# Build rule for target.
shellgrow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shellgrow
.PHONY : shellgrow

# fast build rule for target.
shellgrow/fast:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/build
.PHONY : shellgrow/fast

source/Arrow.o: source/Arrow.cpp.o

.PHONY : source/Arrow.o

# target to build an object file
source/Arrow.cpp.o:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/Arrow.cpp.o
.PHONY : source/Arrow.cpp.o

source/Arrow.i: source/Arrow.cpp.i

.PHONY : source/Arrow.i

# target to preprocess a source file
source/Arrow.cpp.i:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/Arrow.cpp.i
.PHONY : source/Arrow.cpp.i

source/Arrow.s: source/Arrow.cpp.s

.PHONY : source/Arrow.s

# target to generate assembly for a file
source/Arrow.cpp.s:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/Arrow.cpp.s
.PHONY : source/Arrow.cpp.s

source/Tensor.o: source/Tensor.cpp.o

.PHONY : source/Tensor.o

# target to build an object file
source/Tensor.cpp.o:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/Tensor.cpp.o
.PHONY : source/Tensor.cpp.o

source/Tensor.i: source/Tensor.cpp.i

.PHONY : source/Tensor.i

# target to preprocess a source file
source/Tensor.cpp.i:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/Tensor.cpp.i
.PHONY : source/Tensor.cpp.i

source/Tensor.s: source/Tensor.cpp.s

.PHONY : source/Tensor.s

# target to generate assembly for a file
source/Tensor.cpp.s:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/Tensor.cpp.s
.PHONY : source/Tensor.cpp.s

source/allvectors.o: source/allvectors.cpp.o

.PHONY : source/allvectors.o

# target to build an object file
source/allvectors.cpp.o:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/allvectors.cpp.o
.PHONY : source/allvectors.cpp.o

source/allvectors.i: source/allvectors.cpp.i

.PHONY : source/allvectors.i

# target to preprocess a source file
source/allvectors.cpp.i:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/allvectors.cpp.i
.PHONY : source/allvectors.cpp.i

source/allvectors.s: source/allvectors.cpp.s

.PHONY : source/allvectors.s

# target to generate assembly for a file
source/allvectors.cpp.s:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/allvectors.cpp.s
.PHONY : source/allvectors.cpp.s

source/energy.o: source/energy.cpp.o

.PHONY : source/energy.o

# target to build an object file
source/energy.cpp.o:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/energy.cpp.o
.PHONY : source/energy.cpp.o

source/energy.i: source/energy.cpp.i

.PHONY : source/energy.i

# target to preprocess a source file
source/energy.cpp.i:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/energy.cpp.i
.PHONY : source/energy.cpp.i

source/energy.s: source/energy.cpp.s

.PHONY : source/energy.s

# target to generate assembly for a file
source/energy.cpp.s:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/energy.cpp.s
.PHONY : source/energy.cpp.s

source/grow.o: source/grow.cpp.o

.PHONY : source/grow.o

# target to build an object file
source/grow.cpp.o:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/grow.cpp.o
.PHONY : source/grow.cpp.o

source/grow.i: source/grow.cpp.i

.PHONY : source/grow.i

# target to preprocess a source file
source/grow.cpp.i:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/grow.cpp.i
.PHONY : source/grow.cpp.i

source/grow.s: source/grow.cpp.s

.PHONY : source/grow.s

# target to generate assembly for a file
source/grow.cpp.s:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/grow.cpp.s
.PHONY : source/grow.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/shell.o: source/shell.cpp.o

.PHONY : source/shell.o

# target to build an object file
source/shell.cpp.o:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/shell.cpp.o
.PHONY : source/shell.cpp.o

source/shell.i: source/shell.cpp.i

.PHONY : source/shell.i

# target to preprocess a source file
source/shell.cpp.i:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/shell.cpp.i
.PHONY : source/shell.cpp.i

source/shell.s: source/shell.cpp.s

.PHONY : source/shell.s

# target to generate assembly for a file
source/shell.cpp.s:
	$(MAKE) -f CMakeFiles/shellgrow.dir/build.make CMakeFiles/shellgrow.dir/source/shell.cpp.s
.PHONY : source/shell.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... shellgrow"
	@echo "... source/Arrow.o"
	@echo "... source/Arrow.i"
	@echo "... source/Arrow.s"
	@echo "... source/Tensor.o"
	@echo "... source/Tensor.i"
	@echo "... source/Tensor.s"
	@echo "... source/allvectors.o"
	@echo "... source/allvectors.i"
	@echo "... source/allvectors.s"
	@echo "... source/energy.o"
	@echo "... source/energy.i"
	@echo "... source/energy.s"
	@echo "... source/grow.o"
	@echo "... source/grow.i"
	@echo "... source/grow.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/shell.o"
	@echo "... source/shell.i"
	@echo "... source/shell.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

